apiVersion: v1
kind: Service
metadata:
  name: {{ include "grimoire.fullname" . }}
  labels:
    {{- include "grimoire.labels" . | nindent 4 }}
spec:
  type: {{ .Values.networking.type }}
  ports:
    - port: {{ .Values.networking.grimoire.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "grimoire.selectorLabels" . | nindent 4 }}
