apiVersion: v1
kind: Service
metadata:
  name: {{ include "icarius.fullname" . }}
  labels:
    {{- include "icarius.labels" . | nindent 4 }}
spec:
  type: {{ .Values.networking.type }}
  ports:
    - port: {{ .Values.networking.icarius.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "icarius.selectorLabels" . | nindent 4 }}
