apiVersion: v1
kind: Service
metadata:
  name: {{ include "neverending.fullname" . }}
  labels:
    {{- include "neverending.labels" . | nindent 4 }}
spec:
  type: {{ .Values.networking.type }}
  ports:
    - port: {{ .Values.networking.neverending.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "neverending.selectorLabels" . | nindent 4 }}
